// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMYVQw2e9ieqYN2uoBILooKZFF9rfjErA',
    appId: '1:482945734465:android:3061fb8d4692d7598233c0',
    messagingSenderId: '482945734465',
    projectId: 'patientapp-c1863',
    storageBucket: 'patientapp-c1863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKG-9ZYHHvSOXIsT4yTpe4duvIpgKWsq0',
    appId: '1:482945734465:ios:33d1f108bcbb68fa8233c0',
    messagingSenderId: '482945734465',
    projectId: 'patientapp-c1863',
    storageBucket: 'patientapp-c1863.appspot.com',
    iosBundleId: 'com.example.patientapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKG-9ZYHHvSOXIsT4yTpe4duvIpgKWsq0',
    appId: '1:482945734465:ios:b9700a16642c56de8233c0',
    messagingSenderId: '482945734465',
    projectId: 'patientapp-c1863',
    storageBucket: 'patientapp-c1863.appspot.com',
    iosBundleId: 'com.example.patientapp.RunnerTests',
  );
}
